Support converting P-Code IRSBs to AIL blocks
angr/ailment pull request #53
Opened 2020-12-04 05:16 UTC by mborgerson

This is a work-in-progress P-Code IRSB to AIL block converter, with some light refactoring to support both VEX and P-Code in harmony. I have a couple things to fix before this should be merged (e.g. calls, stack pointer analysis stuff, and possibly supporting some more instructions), but in my testing this has worked well for small functions.

<details>
<summary>
A very trivial example
</summary>

Decomp using P-Code (with some angr changes improving block optimization)

```c
void block_A()
{
    unsigned int ir_1;
    unsigned int ir_2;

    if (33 == ECX<4>)
    {
        ir_1 = 0;
    }
    else
    {
        ir_2 = 1;
    }
    return;
}
```

Decomp using VEX

```c
void block_A()
{
    BOT ir_0;
    unsigned int ir_1;
    unsigned int ir_2;

    if (33 != ir_0)
    {
        ir_1 = 1;
    }
    else
    {
        ir_2 = 0;
    }
    return;
}
```
</details>

2021-01-31 06:56 UTC, ltfish requested changes

2021-01-31 06:56 UTC, ltfish commented on ailment/converter_pcode.py
> +
Remove the extra blank line.

2021-01-31 06:57 UTC, ltfish commented
LGTM! Feel free to merge after you remove that blank line.

2021-01-31 07:58 UTC, mborgerson commented on ailment/converter_pcode.py
> +
Will do

2021-02-01 23:34 UTC, mborgerson commented on ailment/converter_pcode.py
> +
Done!

2021-02-01 23:42 UTC, ltfish approved these changes

2021-02-01 23:42 UTC, merged

2021-02-01 23:42 UTC, ltfish commented
Awesome. Thanks!